### PR TITLE
Add DUP functionality

### PR DESCRIPTION
**Pull request by gonzabrusco**
Disclaimer, I did not yet test this but it should work! 

I added a new function to the library that allows you to send duplicate messages. The key to send duplicate messages is to be able to reuse the same packet id of the original message, so I added that functionality too. But I also kept retro-compatibility with previous code. Let me know what you think!

### CODE REVIEW

**Comment by 256dpi** [comment]
Thanks for the PR! I allowed myself to change some things. Will look into merging this in the upcoming days.

**Comment by 256dpi** [comment]
Added tests and fixed the test workflow. Thanks @gonzabrusco for kicking this off!

**Comment by gonzabrusco** [comment]
Thanks for the work! I will check it out. Now I need to pass this new functionality to the Arduino wrapper haha.

**Comment by 256dpi** [comment]
@gonzabrusco No worries, I'll work on that.

**Comment by gonzabrusco** [comment]
Thanks @256dpi !! Since you are working on this I think that there's one little thing that is missing on lwmqtt. When you connect to the broker without a clean session, the connect() function does not inform the user if the broker actually has a session stored or not. You are actually checking that but not passing it to the caller (https://github.com/256dpi/lwmqtt/blob/8ae0aae6ff12f7257e2e9653f2cb2dd746f798c6/src/client.c#L455). Something similar to the Packet ID could be implemented on that function but for the session.

**Comment by gonzabrusco** [comment]
Also I wanted to tell you that on the Arduino version the following check is not needed:

https://github.com/256dpi/arduino-mqtt/blob/eae214b1c2ca0d861037617a0ed0128e3c5ec306/src/MQTTClient.cpp#L30

The overflow will happen but the unsigned arithmetic will give you the correct difference anyway. Check this: https://www.gammon.com.au/millis

**Comment by 256dpi** [comment]
Thanks for the feedback! I changed the connect options to a pointer, now we can use it to store the return code and whether a session was present on the object, similar to the new publish options.

I'm aware of the unsigned integer overflow, but decided to keep the code that way for people that don't know that, to still understand the code.

**Comment by gonzabrusco** [comment]
I understand. Thanks for the work again. I just noticed you are now allowing to send payloads of any size which is a very nice feature!

Could you separate the bufSize parameter on the Arduino version? It now clear that the size of the send buffer should be very small compared to the  receive buffer.

https://github.com/256dpi/arduino-mqtt/blob/eae214b1c2ca0d861037617a0ed0128e3c5ec306/src/MQTTClient.cpp#L163

In fact, do we need really to specify the write buffer? Aren't the MQTT packets (without considering the payload) contained in size?

**Comment by 256dpi** [comment]
Yes, I just added that on the master branch. The topic is still written to the write buffer, which may be longer than 128 for some rare users. We can consider increasing and removing that in a 3.x release.

**Comment by gonzabrusco** [comment]
That was fast!! This week I will be giving a test to everything. I will let you know if I see something. 

Thanks again!!

**Pull request merged**
